require('setting.plugin-config.bufferline')
require('setting.plugin-config.lualine')
require('setting.plugin-config.telescope')
require('setting.plugin-config.treesitter')
require('setting.plugin-config.autopairs')
require('setting.plugin-config.s-which-key')
require('setting.plugin-config.tree')
require('setting.plugin-config.toggleterm')
require('setting.plugin-config.dashboard')
require('setting.plugin-config.project')
require('setting.plugin-config.s-colorizer')
-- require('setting.plugin-config.nvim-comment')
require('setting.plugin-config.lsp-saga')
require('setting.plugin-config.blankline')
require('setting.plugin-config.s-neo-tree')
require('setting.plugin-config.s-null-ls')
-- require('setting.plugin-config.rust-tool')
